### ISSUE TITLE
[$15] UX- All popup forms - Click on another place will close the popup form

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#127]
![image](https://user-images.githubusercontent.com/42398485/49712062-4efde480-fc08-11e8-941c-c852b007ec9b.png)

1. Deploy the App and open (theme: Dark)
2. Select a redis server
3. Click Add new Records
4. Click on another location

**Actual:** Click on another place will close the popup form. If user enters 10-20 items to a form and if user accidentally click on another location will loose all the data

**Expected:** Should not close the popup forms if user click on another location. It has a cancel button also

**Browser(s):** Google Chrome 71 (Windows)

**Comment by iversonLv** [comment]
@ksmacleod99  can I get this ticket?

Thanks.

**Comment by iversonLv** [comment]
For consistency, I disabled such Material dialog feature for all popup.

**Comment by ksmacleod99** [comment]
hey there @iversonLv your PR created a weird bug when I merged it with the master branch. 
Instead of a modal, I get a white bar on the left of the screen. Any thoughts?
<img width="1440" alt="screen shot 2018-12-30 at 8 07 06 pm" src="https://user-images.githubusercontent.com/28678836/50553161-bbe82580-0c6e-11e9-9f7c-9fa2920e7f14.png">

**Comment by ksmacleod99** [comment]
fantastic! thank you so much :)
